# Generated by Django 6.0.2 on 2026-02-13 15:53

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDescendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('ci_solicitante', models.CharField(db_index=True, max_length=20)),
                ('nombres_solicitante', models.CharField(max_length=100)),
                ('nombres_progenitor', models.CharField(max_length=100)),
                ('primer_apellido_progenitor', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido_progenitor', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('codigo_seguridad', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado_certificado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('correlativo', models.IntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Descendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('oficialia', models.CharField(max_length=100)),
                ('libro', models.CharField(max_length=20)),
                ('partida', models.CharField(max_length=20)),
                ('fecha_inscripcion', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('certificado_descendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendientes', to='certificacion.certificadodescendencia')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCertificadoDescendencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('certificado', models.TextField(blank=True, max_length=100, null=True)),
                ('ci_solicitante', models.CharField(db_index=True, max_length=20)),
                ('nombres_solicitante', models.CharField(max_length=100)),
                ('nombres_progenitor', models.CharField(max_length=100)),
                ('primer_apellido_progenitor', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido_progenitor', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_qr', models.TextField(blank=True, max_length=100, null=True)),
                ('codigo_seguridad', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('estado_certificado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=20)),
                ('fecha_emision', models.DateTimeField(blank=True, editable=False)),
                ('correlativo', models.IntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certificacion.oficina')),
            ],
            options={
                'verbose_name': 'historical certificado descendencia',
                'verbose_name_plural': 'historical certificado descendencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacion.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='CorrelativoDescendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_correlativo', models.IntegerField(default=0)),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificacion.oficina')),
            ],
        ),
        migrations.AddField(
            model_name='certificadodescendencia',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificacion.oficina'),
        ),
    ]
