# Generated by Django 6.0.2 on 2026-02-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0003_certificadodescendencia_correlativo_formulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadodescendencia',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificacion.funcionario'),
        ),
        migrations.AddField(
            model_name='historicalcertificadodescendencia',
            name='funcionario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certificacion.funcionario'),
        ),
    ]
