# Generated by Django 6.0.2 on 2026-03-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0004_certificadodescendencia_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descendiente',
            name='sistema',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='descendiente',
            name='fecha_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descendiente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descendiente',
            name='libro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descendiente',
            name='oficialia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='descendiente',
            name='partida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descendiente',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
