# Generated by Django 6.0.2 on 2026-03-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0005_descendiente_sistema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDescargasDescendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('certificado_descendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_descargas_descendencia', to='certificacion.certificadodescendencia')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificacion.funcionario')),
            ],
            options={
                'ordering': ['fecha_descarga'],
            },
        ),
    ]
