# Generated by Django 6.0.2 on 2026-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0007_auditoriasistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadodescendencia',
            name='valorada',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='iniciales',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcertificadodescendencia',
            name='valorada',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
