# Generated by Django 6.0.2 on 2026-04-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0008_certificadodescendencia_valorada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='iniciales',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
